services:
  - type: web
    name: flask-app
    runtime: docker
    plan: free
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 8080
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
